import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for Physical AI & Humanoid Robotics textbook
  textbookSidebar: [
    {
      type: 'category',
      label: 'Foundation: Physical AI Concepts (Weeks 1-2)',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Quarter 1: ROS 2 Fundamentals (Weeks 3-5)',
      items: [
        'module-1/index',
        'module-1/ros2-fundamentals',
      ],
    },
    {
      type: 'category',
      label: 'Quarter 2: Robot Simulation (Weeks 6-7)',
      items: [
        'module-2/index',
        'module-2/robot-simulation',
      ],
    },
    {
      type: 'category',
      label: 'Quarter 3: The AI-Robot Brain (Placeholder)',
      items: [
        'module-3/index',
      ],
    },
    {
      type: 'category',
      label: 'Quarter 4: Vision-Language-Action (Placeholder)',
      items: [
        'module-4/index',
      ],
    },
    {
      type: 'category',
      label: 'Capstone: Integration Project',
      items: [
        'capstone-project/index',
      ],
    },
  ],
};

export default sidebars;
